# Generated by Django 5.0.14 on 2025-11-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='mux_asset_id',
            field=models.CharField(blank=True, help_text='Mux Asset ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='mux_playback_id',
            field=models.CharField(blank=True, help_text='Mux Playback ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, help_text='Legacy video URL (for non-Mux videos)', max_length=500, null=True),
        ),
    ]
