# Generated by Django 5.0.14 on 2025-11-03 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment text content')),
                ('timestamp_seconds', models.PositiveIntegerField(blank=True, help_text='Video timestamp in seconds where this comment was made', null=True)),
                ('is_edited', models.BooleanField(default=False, help_text='Has this comment been edited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.lesson')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lesson', '-created_at'], name='core_commen_lesson__e3bbc9_idx'), models.Index(fields=['parent'], name='core_commen_parent__e30d40_idx')],
            },
        ),
    ]
