# Generated by Django 5.0.14 on 2025-11-08 05:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average rating from reviews', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews'),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, help_text='Optional written review', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False, help_text='Has this review been edited')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide this review from public display')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this review prominently')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', '-created_at'], name='core_course_course__370d08_idx'), models.Index(fields=['course', 'is_hidden'], name='core_course_course__2a38a4_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
