# Generated by Django 5.0.14 on 2025-11-08 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_average_rating_course_total_reviews_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Resource title (e.g., '8-Week Training Plan')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this resource contains')),
                ('file', models.FileField(help_text='PDF file only', upload_to='course_resources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.course')),
            ],
            options={
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['course', 'order'], name='core_course_course__fca435_idx')],
            },
        ),
    ]
