# Generated by Django 5.0.14 on 2025-11-08 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_courseresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='unlock_date',
            field=models.DateField(blank=True, help_text='Date when lesson becomes available (null = immediately available)', null=True),
        ),
        migrations.CreateModel(
            name='LessonUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_unlocks', to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'lesson'], name='core_lesson_user_id_5815d8_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
