# Generated by Django 5.0.14 on 2025-11-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lesson_unlock_date_lessonunlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='unlock_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when lesson becomes available (null = immediately available)', null=True),
        ),
    ]
