# Generated by Django 5.0.14 on 2025-11-08 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_lesson_unlock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon identifier', max_length=50)),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('completion', 'Course Completion'), ('engagement', 'Engagement'), ('watch_time', 'Watch Time'), ('speed', 'Speed'), ('streak', 'Streak')], max_length=50)),
                ('requirement_value', models.IntegerField(blank=True, help_text="Numeric requirement (e.g., 5 for '5 lessons')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earners', to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', '-earned_at'], name='core_userba_user_id_01b142_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
