# Generated by Django 5.0.14 on 2025-11-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_referral_referralcode_referralcredit_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'is_completed'], name='core_lesson_lesson__e27728_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='core_lesson_user_id_324053_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'user', 'is_completed'], name='core_lesson_lesson__c7e4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['course', 'status'], name='core_subscr_course__07c4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'course', 'status'], name='core_subscr_user_id_fce89e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'created_at'], name='core_subscr_status_5ae34e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'updated_at'], name='core_subscr_status_016e8f_idx'),
        ),
    ]
