# Generated by Django 5.0.14 on 2025-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_subscription_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='last_position_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Last playback position for resume'),
        ),
    ]
