# Generated by Django 5.0.14 on 2025-11-21 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_last_position_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_seconds', models.PositiveIntegerField(help_text='Video timestamp in seconds')),
                ('content', models.TextField(help_text='Note content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_notes', to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp_seconds'],
                'indexes': [models.Index(fields=['user', 'lesson'], name='core_videon_user_id_9f1872_idx'), models.Index(fields=['lesson', 'timestamp_seconds'], name='core_videon_lesson__62b149_idx')],
            },
        ),
    ]
