# Generated by Django 5.0.14 on 2025-11-21 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_video_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached subscription count'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_coming_soon',
            field=models.BooleanField(default=False, help_text='Mark as coming soon'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured section'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Free course (no subscription required)'),
        ),
        migrations.AddField(
            model_name='course',
            name='popularity_score',
            field=models.PositiveIntegerField(default=0, help_text='Computed popularity for sorting'),
        ),
        migrations.AddField(
            model_name='course',
            name='release_date',
            field=models.DateTimeField(blank=True, help_text='Release date for coming soon courses', null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
                ('image', models.URLField(blank=True, help_text='Category banner image URL', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this course belongs to', related_name='courses', to='core.category'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'is_coming_soon'], name='core_course_is_publ_dd47d0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured'], name='core_course_is_feat_1feaec_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['popularity_score'], name='core_course_popular_e2da9f_idx'),
        ),
        migrations.AddField(
            model_name='coursenotification',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.course'),
        ),
        migrations.AddField(
            model_name='coursenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'order'], name='core_catego_is_acti_cae9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='core_catego_parent__377746_idx'),
        ),
        migrations.AddIndex(
            model_name='coursenotification',
            index=models.Index(fields=['course', 'notified_at'], name='core_course_course__14d42d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursenotification',
            unique_together={('user', 'course')},
        ),
    ]
