# Generated by Django 5.0.14 on 2025-11-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_category_and_course_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Chapter title (e.g., 'Teep Setup')", max_length=200)),
                ('timestamp_seconds', models.PositiveIntegerField(help_text='Timestamp in seconds from start of video')),
                ('description', models.TextField(blank=True, help_text="Optional description of what's covered")),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.lesson')),
            ],
            options={
                'ordering': ['timestamp_seconds'],
                'indexes': [models.Index(fields=['lesson', 'timestamp_seconds'], name='core_videoc_lesson__4ca5e0_idx')],
                'unique_together': {('lesson', 'timestamp_seconds')},
            },
        ),
    ]
